name: Qt macOS build FIX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        run: brew install qt

      - name: Set Qt PATH (importantíssimo)
        run: |
          echo "/opt/homebrew/opt/qt/bin" >> $GITHUB_PATH

      - name: Check Qt
        run: |
          which qmake
          qmake -v

      - name: Clean old builds
        run: rm -rf build

      - name: Run qmake correctly
        run: |
          qmake InputRedirectionClient.pro -spec macx-clang CONFIG+=release

      - name: Build
        run: |
          make -j$(sysctl -n hw.ncpu)
