name: Build Qt macOS (simple)

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        run: brew install qt

      - name: Add Qt to PATH
        run: echo "/opt/homebrew/opt/qt/bin" >> $GITHUB_PATH

      - name: Check qmake
        run: qmake -v

      - name: Build (qmake)
        run: |
          qmake
          make

      - name: Find output
        run: find . -type f -perm +111
